language: r
sudo: required
dist: trusty
cache: packages
r_check_args: "--as-cran"
os:
- linux
- osx
addons:
  apt:
    packages:
    - libssh-dev
r_packages:
- covr
- devtools
before_install:
- openssl aes-256-cbc -K $encrypted_62787b32fc49_key -iv $encrypted_62787b32fc49_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- ssh-add ./deploy_key
after_success:
- R -e 'covr::codecov()'
